### ISSUE TITLE
Title and message do not function

### ISSUE THREAD

**Issue by Fmstrat** [cristianoccazinsp/react-native-foreground-service#16]
When using `startService` or `updateNotification` the `title` and `message` are not displayed in the notification. You always get:

```
"Service" is running
Tap for more information or to stop the app.
```

**Comment by Fmstrat** [comment]
Could be related: https://stackoverflow.com/questions/61738137/startforeground-notification-does-not-show-title-or-content

**Comment by cristianoccazinsp** [comment]
Hey, thanks, we will take a look. I'm no longer actively maintaining this but sometime will review this and the PRs shortly.
