### ISSUE TITLE
Icon values ignored

### ISSUE THREAD

**Issue by KevinSumnerUCT** [cristianoccazinsp/react-native-foreground-service#2]
I added icon and largeIcon to the notificationConfig and the notification continues to show the default image.

The title, display text etc doesn't seem to be showing in the notification: It looks like a full default notification.

**Comment by cristianoccazinsp** [comment]
Are you sure the files for the icons were valid? This was carried over the original library and I have not really tried it out. However, I can tell you that adding files to `app/src/main/res/mipmap-hdpi` (and the other resolution folders) does indeed work. 

You need to add `ic_launcher.png` and `ic_notification.png` to the above folders.
